name: 'Build and push Docker image'
description: 'Builds and pushes a Docker image to Container Registry'
inputs:
  registry:
    description: 'Container Registry'
    required: false
  username:
    description: 'Container Registry Username'
    required: true
  password:
    description: 'Container Registry Password'
    required: true
  image_name:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Docker image tags'
    required: true
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: './Dockerfile'
  platforms:
    description: 'Platforms to build for'
    required: false
    default: 'linux/amd64,linux/arm64,linux/arm/v7'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.4.0

    - name: Login to CR
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Prepare Docker tags and labels
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ inputs.image_name }}
        tags: type=sha

    - name: Build and push to CR
      uses: docker/build-push-action@v6.4.1
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.tags }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
