name: 'Deploy to GKE'
description: 'Deploys a Docker image to Google Kubernetes Engine'
inputs:
  service_account_key:
    description: 'Google Service Account Key'
    required: true
  project_id:
    description: 'Google Cloud Platform Project ID'
    required: true
  cluster_name:
    description: 'Google Kubernetes Engine Cluster Name'
    required: true
  location:
    description: 'Google Kubernetes Engine Cluster Location'
    required: true
  template_path:
    description: 'Path to the template file'
    required: false
    default: 'kube.template.yml'
  vars:
    description: 'Dictionary of variables to pass to the template'
    required: false
    default: ''
  rollout_status_wait:
    description: 'Wait for rollout to complete'
    required: false
    default: ''
  pre_apply:
    description: 'Command to run before applying the template'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.service_account_key }}

    - name: Get the GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.8.2
      with:
        project_id: ${{ inputs.project_id }}
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}

    - name: Render template
      uses: chuhlomin/render-template@v1.9
      with:
        template: ${{ inputs.template_path }}
        result_path: rendered_template.yml
        vars: ${{ inputs.vars }}

    - name: Pre-apply
      shell: bash
      if: ${{ inputs.pre_apply }}
      run: ${{ inputs.pre_apply }}

    - name: Apply
      shell: bash
      run: kubectl apply -f rendered_template.yml

    - name: Wait for rollout
      shell: bash
      if: ${{ inputs.rollout_status_wait }}
      run: kubectl rollout status ${{ inputs.rollout_status_wait }}
