name: 'Pull, retag and push Docker image'
description: 'Pulls a Docker image, retags it and pushes it to the same registry'
inputs:
  registry:
    description: 'Container Registry'
    required: false
  username:
    description: 'Container Registry Username'
    required: true
  password:
    description: 'Container Registry Password'
    required: true
  image_name:
    description: 'Docker image name'
    required: true
  src-tag:
    description: 'Docker image tag to pull'
    required: true
  tags:
    description: 'New Docker image tags to add'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to CR
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Tag image
      shell: bash
      run: |
        for tag in ${{ inputs.tags }}; do
          docker buildx imagetools create -t ${{ inputs.image_name }}:$tag ${{ inputs.image_name }}:${{ inputs.src-tag }}
        done
